### ISSUE TITLE
fix: generate declarations for directory and extension-aliased lib inputs

### ISSUE THREAD

**Issue by exKAZUu** [WillBooster/build-ts#671]
## Problem

`build-ts lib` passes `--input` paths verbatim into the generated tsconfig's `files`, so inputs the bundler resolves but `tsc`/`tsgo` cannot take literally fail during declaration generation:

- a directory input (e.g. `--input src/folder`, resolved by Rolldown to `src/folder/index.ts`) → `error TS6231: Could not resolve the path ... with the extensions: '.ts', '.tsx', ...`
- a `.js` specifier aliased to a `.ts` source (e.g. `--input src/index.js`) → `error TS6504: File ... is a JavaScript file. Did you mean to enable the 'allowJs' option?`

This is pre-existing behavior, not introduced by #669: reproduced with `main`'s `src/commands/build/build.ts` in place, `build-ts lib --input <fixture>/src/folder` fails with the same TS6231.

## Proposed fix

Resolve each input to its actual existing source file (applying the bundler's `extensions` / `extensionAlias` candidates and directory→`index` resolution) before writing them into the generated tsconfig's `files`. Extracting that resolution into its own module avoids a circular import between `build.ts` and `typeScript.ts`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
